### ISSUE TITLE
[Feature request] Update csslint-cli

### ISSUE THREAD

**Issue by Kristinita** [dmi3y/csslint-cli#2]
### 1. Request

It would be nice, if you update `csslint-cli`. Now last edit in your repository date 3 years ago.

### 2. Justification

I use your CLI, not [**default csslint CLI**](https://github.com/CSSLint/csslint), because I can use one `.csslintrc` file in root directory of my projects. Yes, I have seen [**your pull-request for csslint**](https://github.com/CSSLint/csslint/pull/502), but I think, that I'll still have problems with TravisCI or AppVeyor csslint integration.

By this reason it would be nice, if csslint-cli will be longer maintained.

### 3. Actual behavior

For example, I have a file [**`sublime-text.css`**](https://github.com/Kristinita/KristinitaPelican/blob/master/themes/sashapelican/static/css/sections/sublime-text.css).

```javascript
D:\…a\themes\sashapelican\static\css\sections>csslint-cli sublime-text.css

+-.\sublime-text.css: 3 issue(s):
|
|   L84:C5 . . . background: rgba(255, 228, 181, 0.99);
|   WARN: Fallback background (hex or RGB) should precede RGBA background.(fallback-colors)
|
|   L89:C5 . . . background: rgba(255, 228, 181, 0.99);
|   WARN: Fallback background (hex or RGB) should precede RGBA background.(fallback-colors)
|
|   L94:C5 . . . background: rgba(255, 228, 181, 0.99);
|   WARN: Fallback background (hex or RGB) should precede RGBA background.(fallback-colors)
|
+-.\sublime-text.css
```

### 4. Expected behavior

I get extra [**order-alphabetical**](https://github.com/CSSLint/csslint/wiki/Disallow-non-alphabetical) rule output.

```c++
D:\…a\themes\sashapelican\static\css\sections>csslint sublime-text.css


csslint: There are 7 problems in D:\Kristinita\themes\sashapelican\static\css\sections\sublime-text.css.

sublime-text.css
1: warning at line 59, col 1
Rule doesn't have all its properties in alphabetical order.
blockquote {

sublime-text.css
2: warning at line 84, col 5
Fallback background (hex or RGB) should precede RGBA background.
    background: rgba(255, 228, 181, 0.99);

sublime-text.css
3: warning at line 89, col 5
Fallback background (hex or RGB) should precede RGBA background.
    background: rgba(255, 228, 181, 0.99);

sublime-text.css
4: warning at line 94, col 5
Fallback background (hex or RGB) should precede RGBA background.
    background: rgba(255, 228, 181, 0.99);

sublime-text.css
5: warning at line 102, col 1
Rule doesn't have all its properties in alphabetical order.
.tooltipster-punk-purple .tooltipster-box

sublime-text.css
6: warning at line 110, col 1
Rule doesn't have all its properties in alphabetical order.
.tooltipster-punk-aquamarine .tooltipster-box

sublime-text.css
7: warning at line 126, col 1
Rule doesn't have all its properties in alphabetical order.
.SashaEpigraph {
```

Thanks.

**Comment by dmi3y** [comment]
Hey @Kristinita! Thanks for feedback. Will certainly take a look into it.

**Comment by dmi3y** [comment]
Upgraded csslint and bumped up version of package to match csslint (1.0.5). It should have all newest features now.
